package HospitalModel;
import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;

public class HospitalSys extends ViewableDigraph {
	String IN = "IN", OUT = "OUT", outOne = "1OUT", outTwo = "2OUT", outThree = "3OUT";
	public HospitalSys() {
		super("Hospital");
		addInport(IN);
		addOutport(OUT);
		ViewableAtomic NormalPatient = new patientGenr("NormalPatient");
		add(NormalPatient);
		ViewableAtomic EmergencyPatient = new patientGenr("EmergencyPatient");
		add(EmergencyPatient);
		ViewableAtomic Receptionist = new HealthcareReceptionist("Receptionist");
		add(Receptionist);
		ViewableAtomic DoctorOne = new availableDoctors("DoctorOne");
		add(DoctorOne);
		ViewableAtomic DoctorTwo = new availableDoctors("DoctorTwo");
		add(DoctorTwo);
		ViewableAtomic DoctorThree = new availableDoctors("DoctorThree");
		add(DoctorThree);
		ViewableAtomic PatientDoctorController = new PatientDoctorController("PatientDoctorController");
		add(PatientDoctorController);
		ViewableAtomic pharmacy = new pharmacy("pharmacy");
		add(pharmacy);
		addCoupling(this,IN,NormalPatient,IN);
		addCoupling(this,IN,EmergencyPatient,IN);
		addCoupling(NormalPatient, OUT, Receptionist, IN);
		addCoupling(EmergencyPatient, OUT, Receptionist, IN);
		addCoupling(Receptionist,outOne,DoctorOne,IN);
		addCoupling(Receptionist,outTwo,DoctorTwo,IN);
		addCoupling(Receptionist,outThree,DoctorThree,IN);
		addCoupling(DoctorOne,OUT,PatientDoctorController,IN);
		addCoupling(DoctorTwo,OUT,PatientDoctorController,IN);
		addCoupling(DoctorThree,OUT,PatientDoctorController,IN);
		addCoupling(PatientDoctorController, OUT, pharmacy, IN);
		addCoupling(pharmacy, OUT, Receptionist, IN);
		addCoupling(PatientDoctorController, OUT, Receptionist, IN);
		addCoupling(pharmacy, OUT, this, OUT);
		
		
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(828, 519);
        if((ViewableComponent)withName("DoctorOne")!=null)
             ((ViewableComponent)withName("DoctorOne")).setPreferredLocation(new Point(312, 110));
        if((ViewableComponent)withName("pharmacy")!=null)
             ((ViewableComponent)withName("pharmacy")).setPreferredLocation(new Point(315, 410));
        if((ViewableComponent)withName("DoctorTwo")!=null)
             ((ViewableComponent)withName("DoctorTwo")).setPreferredLocation(new Point(310, 203));
        if((ViewableComponent)withName("PatientDoctorController")!=null)
             ((ViewableComponent)withName("PatientDoctorController")).setPreferredLocation(new Point(540, 67));
        if((ViewableComponent)withName("DoctorThree")!=null)
             ((ViewableComponent)withName("DoctorThree")).setPreferredLocation(new Point(310, 269));
        if((ViewableComponent)withName("EmergencyPatient")!=null)
             ((ViewableComponent)withName("EmergencyPatient")).setPreferredLocation(new Point(-25, 314));
        if((ViewableComponent)withName("Receptionist")!=null)
             ((ViewableComponent)withName("Receptionist")).setPreferredLocation(new Point(132, 210));
        if((ViewableComponent)withName("NormalPatient")!=null)
             ((ViewableComponent)withName("NormalPatient")).setPreferredLocation(new Point(-17, 145));
    }
}
